### ISSUE TITLE
change menu to keyboard input plz!

### ISSUE THREAD

**Issue by ca3tiel** [DyAxy/V2Board_Python_Bot#5]
hi
first of all...ty for bot..its so good
I wanted to request that you change the menu to keyboard type..This is much more user-friendly
and also its nice if u can change /bind in to tow steps..1 time request for email address and new time for pass
ty so much

**Comment by Mayomi** [comment]
For question 1, change the menu to keyboard type.
I made it for private and in-group.So for in-group compatible, I won't change it.
Then question 2.
Why need 2 steps for bind? I'm confused about it.

**Comment by DyAxy** [comment]
For question 1, change the menu to keyboard type.
I made it for private and in-group.So for in-group compatible, I won't change it.
Then question 2.
Why need 2 steps for bind? I'm confused about it.
