### ISSUE TITLE
The single spam bot has paid many times

### ISSUE THREAD

**Issue by Github-Aiko** [DyAxy/V2Board_Python_Bot#6]
BOT spam pays a lot for the Master Latest version of the ODER

**Comment by DyAxy** [comment]
So can you show me console log or screenshot?

**Comment by Github-Aiko** [comment]
<img width="797" alt="Screen Shot 2023-01-30 at 12 50 35" src="https://user-images.githubusercontent.com/100770712/215397589-262c903d-6773-44ab-95a9-8b41eb8e9e3c.png">

**Comment by Github-Aiko** [comment]
logs

**Comment by Github-Aiko** [comment]
<img width="134" alt="Screen Shot 2023-01-30 at 12 51 45" src="https://user-images.githubusercontent.com/100770712/215397735-6f1d551e-4ebb-4153-a8bf-93a3b6f60015.png">
And 1 minute spam a successful order once

**Comment by DyAxy** [comment]
Look at third last line.
_Chat not found_
Check your admin_id at config.yaml, make sure configured admin_id already.

**Comment by Github-Aiko** [comment]
It done all thx
